package org.mpisws.jmc.checker;

import java.util.HashMap;

/**
 * The JmcModelCheckerReport class represents a report generated by the JMC model checker.
 */
public class JmcModelCheckerReport {

    private final HashMap<String, Object> reportData;

    /**
     * Constructs a new JmcModelCheckerReport object.
     */
    public JmcModelCheckerReport() {
        this.reportData = new HashMap<>();
    }

    public void setTotalTimeMillis(Long totalTimeMillis) {
        setParam("totalTimeMillis", totalTimeMillis);
    }

    public Long getTotalTimeMillis() {
        return getParam("totalTimeMillis");
    }

    public void setErrorIteration(Integer errorIteration) {
        setParam("errorIteration", errorIteration);
    }

    public Integer getErrorIteration() {
        return getParam("errorIteration");
    }

    public void setErrorMessage(String errorMessage) {
        setParam("errorMessage", errorMessage);
    }

    public String getErrorMessage() {
        return getParam("errorMessage");
    }

    public void setReplaySeed(Long replaySeed) {
        setParam("replaySeed", replaySeed);
    }

    public Long getReplaySeed() {
        return getParam("replaySeed");
    }

    public void setParam(String key, Object value) {
        this.reportData.put(key, value);
    }

    @SuppressWarnings("unchecked")
    public <T> T getParam(String key) {
        if (!reportData.containsKey(key)) {
            return null;
        }
        return (T) reportData.get(key);
    }
}
