package org.mpi_sws.jmc.checker;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.mpi_sws.jmc.checker.exceptions.JmcCheckerException;
import org.mpi_sws.jmc.runtime.HaltCheckerException;
import org.mpi_sws.jmc.runtime.HaltExecutionException;
import org.mpi_sws.jmc.runtime.HaltTaskException;
import org.mpi_sws.jmc.runtime.JmcRuntime;
import org.mpi_sws.jmc.runtime.JmcRuntimeConfiguration;
import org.mpi_sws.jmc.runtime.JmcRuntimeEvent;
import org.mpi_sws.jmc.util.ExceptionUtil;

/**
 * Manages a JMC model-checking run from start to finish.
 *
 * <p>Given a {@link JmcCheckerConfiguration} and a {@link JmcTestTarget} (the program under test),
 * {@code JmcModelChecker} derives a runtime configuration, sets up the {@link JmcRuntime}, and drives
 * the exploration loop — running the target once per iteration under the runtime's control until the
 * iteration budget or timeout is reached, or a violation is found. It collects the outcome into a
 * {@link JmcModelCheckerReport} and maps the runtime's halt signals ({@link HaltTaskException}, {@link
 * HaltExecutionException}, {@link HaltCheckerException}) onto the checker's {@link JmcCheckerException}
 * hierarchy. It is invoked from the JUnit integration via {@code JmcTestExecutor}; the checker itself
 * has no dependency on JUnit or reflection, seeing only a {@link JmcTestTarget}.
 */
public class JmcModelChecker {

    /** Logger for run-level progress and error reporting. */
    private static final Logger LOGGER = LogManager.getLogger(JmcModelChecker.class);

    /** The immutable configuration driving this run (iterations, strategy, timeout, ...). */
    private final JmcCheckerConfiguration config;

    /**
     * Constructs a new JMC model checker with the given configuration.
     *
     * @param config the configuration to use
     */
    public JmcModelChecker(JmcCheckerConfiguration config) {
        this.config = config;
    }

    /**
     * Runs the full model-checking exploration for a test target and returns its report.
     *
     * <p>Derives a {@link JmcRuntimeConfiguration} from {@link #config} (instantiating the scheduling
     * strategy), sets up the {@link JmcRuntime}, and repeatedly: initializes an iteration, invokes the
     * target (one interleaving), reports a {@code FINISH_EVENT} for the main task, and resets. The loop
     * handles the runtime's halt signals — a {@link HaltTaskException} is logged and the run continues;
     * a {@link HaltExecutionException} requesting re-execution is retried without being counted, while
     * other flavors are recorded as errors; a plain assertion error triggers {@link
     * JmcRuntime#recordTrace()} and ends the run as a bug. Iteration count and timeout are checked each
     * pass, raising {@link HaltCheckerException#ok()} / {@link HaltCheckerException#timeout()} to stop.
     * On normal completion or timeout the report is finalized; other failures are rethrown as {@link
     * JmcCheckerException}. The runtime is always torn down. (This method does not itself perform
     * bytecode instrumentation — that is done by the agent at class load.)
     *
     * @param target the test target to check (its {@code invoke()} runs the instrumented program)
     * @return the report generated by the model checker
     * @throws JmcCheckerException if model checking fails (a violation, an unexpected error, or an
     *     invalid configuration surfaced while deriving the runtime configuration)
     */
    public JmcModelCheckerReport check(JmcTestTarget target) throws JmcCheckerException {
        JmcRuntimeConfiguration runtimeConfig = config.toRuntimeConfiguration();
        JmcModelCheckerReport report = new JmcModelCheckerReport(runtimeConfig.getReportPath());
        report.setupReportPath();
        long startTime = System.currentTimeMillis();
        long timeoutMarker = 0L;
        if (config.getTimeout() != null) {
            timeoutMarker = startTime + config.getTimeout().toMillis();
        }
        JmcRuntime.setup(runtimeConfig);
        int numIterations = config.getNumIterations();
        int iteration = 0;
        try {
            LOGGER.info("JMC checker started");
            while (true) {
                boolean successfulIteration = true;
                try {
                    LOGGER.debug("Running iteration {}", iteration);
                    JmcRuntime.initIteration(iteration, report);
                    target.invoke();
                    JmcRuntimeEvent mainEndEvent =
                            new JmcRuntimeEvent.Builder()
                                    .type(JmcRuntimeEvent.Type.FINISH_EVENT)
                                    .taskId(1L)
                                    .build();
                    JmcRuntime.updateEvent(mainEndEvent);
                } catch (HaltTaskException e) {
                    LOGGER.debug(
                            "Halting execution: {} due to main thread halted: {}",
                            iteration,
                            e.getMessage());
                } catch (HaltExecutionException e) {
                    if (e.isReexecutionNeeded()) {
                        // Since we are going to re-execute, do not count this iteration
                        numIterations++;
                    } else {
                        report.setErrorIteration(iteration);
                        report.setErrorMessage(e.getMessage());
                        LOGGER.error(
                                "Halting execution: {} due to exception: {}",
                                iteration,
                                e.getMessage());
                        throw e;
                    }
                } catch (Exception e) {
                    successfulIteration = false;
                    // Catchall for any other exceptions that may occur
                    report.setErrorIteration(iteration);
                    if (ExceptionUtil.isAssertionError(e)) {
                        report.setErrorMessage(
                                String.format(
                                        "Halting execution: %d due to assertion error: %s",
                                        iteration, e.getMessage()));
                        LOGGER.error(
                                "Assertion error in iteration {}: {}", iteration, e.getMessage());
                        JmcRuntime.recordTrace();
                        throw HaltCheckerException.error(
                                "Assertion error in iteration " + iteration + ": " + e.getMessage(),
                                e);
                    } else {
                        throw e;
                    }
                } finally {
                    JmcRuntime.resetIteration(iteration);
                    if (iteration % 50000 == 0) {
                        LOGGER.info("Completed {} iterations", iteration);
                        System.gc();
                    }
                    iteration++;
                    if (numIterations != 0 && iteration >= numIterations && successfulIteration) {
                        throw HaltCheckerException.ok();
                    }
                    long curTime = System.currentTimeMillis();
                    if (timeoutMarker != 0L && curTime > timeoutMarker && successfulIteration) {
                        report.setErrorIteration(iteration);
                        String errorMessage =
                                String.format("Halting execution: %d due to timeout", iteration);
                        report.setErrorMessage(errorMessage);
                        LOGGER.error(errorMessage);
                        throw HaltCheckerException.timeout();
                    }
                }
            }
        } catch (HaltCheckerException e) {
            if (e.isOkay()) {
                int totalIterations = iteration - 1;
                report.setTotalIterations(totalIterations);
                LOGGER.info("Model checking completed covering: {} iterations", totalIterations);
            } else if (e.isTimeout()) {
                int totalIterations = iteration - 1;
                report.setTotalIterations(totalIterations);
                LOGGER.error("Model checker timeout out: {}", e.getMessage());
            } else {
                report.setErrorIteration(-1);
                report.setErrorMessage(String.format("Model checking failed: %s", e.getMessage()));
                LOGGER.error("Model checking failed: {}", e.getMessage());
                if (e.getCause() != null) {
                    throw new JmcCheckerException(e.getMessage(), e.getCause());
                } else {
                    throw new JmcCheckerException(e.getMessage());
                }
            }
        } catch (Exception e) {
            report.setErrorIteration(-1);
            report.setErrorMessage(
                    String.format(
                            "Model checking failed with unexpected exception: %s", e.getMessage()));
            LOGGER.error("Model checking failed with unexpected exception: {}", e.getMessage());
            if (e.getCause() != null) {
                throw new JmcCheckerException(e.getMessage(), e.getCause());
            } else {
                throw new JmcCheckerException(e.getMessage(), e);
            }
        } finally {
            long endTime = System.nanoTime();
            JmcRuntime.tearDown(report);
            report.setTotalTimeMillis(endTime - startTime);
            int totalIterations = report.getTotalIterations();
            LOGGER.info("Model checking explored: {} completed iterations", totalIterations -
                    report.getBlockedIterations());
            LOGGER.info("Model checking explored: {} blocked iterations", report.getBlockedIterations());
        }
        return report;
    }

    /**
     * Reproduces a single recorded schedule for a test target instead of exploring.
     *
     * <p>Sets up the runtime for replay via {@link JmcRuntime#setupReplay(JmcRuntimeConfiguration)}
     * (which requires a replay-capable strategy) and runs exactly one iteration (initialize, invoke
     * the target, report the main {@code FINISH_EVENT}, reset). It catches {@link HaltTaskException},
     * {@link HaltExecutionException}, {@link AssertionError}, and {@link HaltCheckerException} to log
     * the outcome into a throwaway report, and always tears the runtime down. It returns nothing —
     * replay is for observing the reproduced run. Used for methods annotated with {@code @JmcReplay}.
     *
     * @param target the test target to replay
     * @throws JmcCheckerException if an error occurs during replay (e.g. deriving the runtime
     *     configuration or setting up replay)
     */
    public void replay(JmcTestTarget target) throws JmcCheckerException {
        JmcRuntimeConfiguration runtimeConfig = config.toRuntimeConfiguration();
        JmcRuntime.setupReplay(runtimeConfig);
        long startTime = System.currentTimeMillis();

        JmcModelCheckerReport dummyReport =
                new JmcModelCheckerReport(runtimeConfig.getReportPath());
        try {
            JmcRuntime.initIteration(0, dummyReport);
            target.invoke();
            JmcRuntimeEvent mainEndEvent =
                    new JmcRuntimeEvent.Builder()
                            .type(JmcRuntimeEvent.Type.FINISH_EVENT)
                            .taskId(1L)
                            .build();
            JmcRuntime.updateEvent(mainEndEvent);
            JmcRuntime.resetIteration(0);
        } catch (HaltTaskException e) {
            LOGGER.debug("Halting execution: due to main thread halted: {}", e.getMessage());
        } catch (HaltExecutionException e) {
            dummyReport.setErrorMessage(e.getMessage());
            LOGGER.error("Halting execution: due to exception: {}", e.getMessage());
        } catch (AssertionError e) {
            dummyReport.setErrorMessage(
                    String.format("Halting execution due to assertion error: %s", e.getMessage()));
            LOGGER.error("Assertion error: {}", e.getMessage());
        } catch (HaltCheckerException e) {
            if (e.isOkay()) {
                LOGGER.info("Replay completed successfully.");
            } else {
                dummyReport.setErrorIteration(-1);
                dummyReport.setErrorMessage(String.format("Replaying failed: %s", e.getMessage()));
                LOGGER.error("Replaying failed: {}", e.getMessage());
            }
        } finally {
            long endTime = System.currentTimeMillis();
            JmcRuntime.tearDown(dummyReport);
            dummyReport.setTotalTimeMillis(endTime - startTime);
        }
    }
}
