package org.mpi_sws.jmc.checker;

import org.mpi_sws.jmc.util.FileUtil;

import java.util.HashMap;

/**
 * The JmcModelCheckerReport class represents a report generated by the JMC model checker.
 */
public class JmcModelCheckerReport {

    private final HashMap<String, Object> reportData;

    private final String reportPath;

    /**
     * Constructs a new JmcModelCheckerReport object.
     */
    public JmcModelCheckerReport(String reportPath) {
        this.reportPath = reportPath;
        this.reportData = new HashMap<>();
    }

    public void setupReportPath() {
        FileUtil.unsafeEnsurePath(reportPath);
    }

    public String getReportPath() {
        return reportPath;
    }

    public void setTotalTimeMillis(Long totalTimeMillis) {
        setParam("totalTimeMillis", totalTimeMillis);
    }

    public Long getTotalTimeMillis() {
        return getParam("totalTimeMillis");
    }

    public void setErrorIteration(Integer errorIteration) {
        setParam("errorIteration", errorIteration);
    }

    public Integer getErrorIteration() {
        return getParam("errorIteration");
    }

    public void setErrorMessage(String errorMessage) {
        setParam("errorMessage", errorMessage);
    }

    public String getErrorMessage() {
        return getParam("errorMessage");
    }

    public void setReplaySeed(Long replaySeed) {
        setParam("replaySeed", replaySeed);
    }

    public Long getReplaySeed() {
        return getParam("replaySeed");
    }

    public void setTotalIterations(Integer totalIterations) {
        setParam("totalIterations", totalIterations);
    }

    public Integer getTotalIterations() {
        Object o = getParam("totalIterations");
        if (o == null) {
            return 0;
        }
        return (Integer) o;
    }

    public void setBlockedIterations(Integer blockedIterations) {
        setParam("blockedIterations", blockedIterations);
    }

    public Integer getBlockedIterations() {
        Object o = getParam("blockedIterations");
        if (o == null) {
            return 0;
        }
        return (Integer) o;
    }

    public void setParam(String key, Object value) {
        this.reportData.put(key, value);
    }

    @SuppressWarnings("unchecked")
    public <T> T getParam(String key) {
        if (!reportData.containsKey(key)) {
            return null;
        }
        return (T) reportData.get(key);
    }
}
