package org.mpi_sws.jmc.solver;

import org.mpi_sws.jmc.api.symbolic.array.SymArrayVariable;
import org.mpi_sws.jmc.api.symbolic.bool.JmcBooleanFormula;
import org.mpi_sws.jmc.api.symbolic.bool.SymBoolVariable;
import org.mpi_sws.jmc.api.symbolic.integer.SymIntVariable;
import org.sosy_lab.common.ShutdownManager;
import org.sosy_lab.common.configuration.Configuration;
import org.sosy_lab.common.configuration.InvalidConfigurationException;
import org.sosy_lab.common.log.BasicLogManager;
import org.sosy_lab.common.log.LogManager;
import org.sosy_lab.java_smt.SolverContextFactory;
import org.sosy_lab.java_smt.api.*;

import java.util.HashMap;
import java.util.Map;

/**
 * The SymbolicSolver class is a core component designed for solving symbolic formulas within the program under the test.
 * It encapsulates the functionality for manipulating and solving symbolic representations of boolean and integer
 * variables. This class leverages the JavaSMT API to interface with various SMT (Satisfiability Modulo Theories) solvers,
 * providing a unified API for theorem proving tasks.
 * <p>
 * The class supports operations such as solving symbolic formulas, negating formulas, and creating dependency formulas
 * from a list of symbolic operations. It allows for the dynamic selection of SMT solvers based on the provided solver type,
 * enabling flexibility in choosing the underlying solver based on the specific requirements of the verification task.
 * <p>
 * SymbolicSolver initializes with a configuration, a logging manager, and a shutdown manager to handle the lifecycle
 * of the solver context. It provides methods to access and manipulate symbolic variables (both boolean and integer),
 * facilitating the creation of complex symbolic expressions that programmer can use.
 */
public abstract class SymbolicSolver {

    /**
     * {@link #config} used to store the configuration settings for the solver context.
     */
    private final Configuration config;

    /**
     * {@link #logger} used to manage logging and output messages from the solver.
     */
    private final LogManager logger;

    /**
     * {@link #shutdown} used to manage the shutdown and cleanup of the solver context.
     */
    private final ShutdownManager shutdown;

    /**
     * {@link #symIntVariableMap} used to store the mapping of symbolic integer variables to their names.
     */
    public Map<String, SymIntVariable> symIntVariableMap = new HashMap<>();

    /**
     * {@link #symBoolVariableMap} used to store the mapping of symbolic boolean variables to their names.
     */
    public Map<String, SymBoolVariable> symBoolVariableMap = new HashMap<>();

    /**
     * {@link #symArrayVariableMap} used to store the mapping of symbolic array variables to their names.
     */
    public Map<String, SymArrayVariable> symArrayVariableMap = new HashMap<>();
    /**
     * {@link #context} used to store the solver context for interacting with the SMT solver.
     */
    protected SolverContext context;

    /**
     * {@link #fmgr} used to access the formula manager for creating and manipulating formulas.
     */
    protected FormulaManager fmgr;

    /**
     * {@link #bmgr} used to access the boolean formula manager for boolean operations.
     */
    protected BooleanFormulaManager bmgr;

    /**
     * {@link #imgr} used to access the integer formula manager for integer operations.
     */
    protected IntegerFormulaManager imgr;

    /**
     * {@link #bmgr} used to access the array formula manager for array operations.
     */
    protected ArrayFormulaManager amgr;

    /**
     * {@link #model} used to store the model generated by the solver for a satisfiable formula.
     */
    protected Model model;

    /** Whether the active prover currently holds no constraints (a fresh context). */
    private boolean freshProver = true;

    /** Cumulative time (ns) spent in solver operations, for reporting. */
    private long solverTime = 0L;

    /**
     * Constructs a new instance of the SymbolicSolver class with the default SMT solver type (SMTInterpol).
     */
    public SymbolicSolver() {
        this(SMTSolverTypes.Z3); // Default to Z3 solver
    }

    /**
     * Constructs a new instance of the SymbolicSolver class with the specified SMT solver type.
     *
     * @param type the type of SMT solver to use for solving symbolic formulas.
     */
    public SymbolicSolver(SMTSolverTypes type) {
        SolverContextFactory.Solvers solverType = findSolverType(type);
        try {
            long startTime = System.nanoTime();
            config = Configuration.builder().build();
            logger = BasicLogManager.create(config);
            shutdown = ShutdownManager.create();
            context = SolverContextFactory.createSolverContext(
                    config, logger, shutdown.getNotifier(), solverType
            );
            fmgr = context.getFormulaManager();
            bmgr = fmgr.getBooleanFormulaManager();
            imgr = fmgr.getIntegerFormulaManager();
            amgr = fmgr.getArrayFormulaManager();
            long endTime = System.nanoTime();
            advanceSolverTime(endTime - startTime);
        } catch (InvalidConfigurationException e) {
            throw new RuntimeException("Error creating solver context", e);
        }
    }

    /**
     * Adds the given elapsed time (ns) to the cumulative solver time.
     *
     * @param time the elapsed time in nanoseconds.
     */
    protected void advanceSolverTime(long time) {
        solverTime += time;
    }

    /**
     * Returns the cumulative time (ns) spent in solver operations.
     *
     * @return the total solver time in nanoseconds.
     */
    public long getSolverTime() {
        return solverTime;
    }

    /**
     * Finds the corresponding SolverContextFactory.Solvers enum value for the given SMTSolverTypes enum value.
     *
     * @param type the type of SMT solver to find the corresponding enum value for.
     * @return the corresponding SolverContextFactory.Solvers enum value.
     */
    public SolverContextFactory.Solvers findSolverType(SMTSolverTypes type) {
        if (type == null) {
            throw new NullPointerException("type is null");
        }
        return switch (type) {
            case OPENSMT -> SolverContextFactory.Solvers.OPENSMT;
            case MATHSAT5 -> SolverContextFactory.Solvers.MATHSAT5;
            case SMTINTERPOL -> SolverContextFactory.Solvers.SMTINTERPOL;
            case Z3 -> SolverContextFactory.Solvers.Z3;
            case PRINCESS -> SolverContextFactory.Solvers.PRINCESS;
            case BOOLECTOR -> SolverContextFactory.Solvers.BOOLECTOR;
            case CVC4 -> SolverContextFactory.Solvers.CVC4;
            case CVC5 -> SolverContextFactory.Solvers.CVC5;
            case YICES2 -> SolverContextFactory.Solvers.YICES2;
            case OFF -> throw new IllegalArgumentException("Solver type cannot be OFF");
        };
    }

    /**
     * Returns the number of constraints currently on the active prover's stack.
     *
     * @return the constraint-stack depth.
     */
    public abstract int size();

    /**
     * Solves the given symbolic formula and returns the result.
     *
     * @param operation the symbolic operation containing the formula to solve.
     * @return true if the formula is satisfiable, false otherwise.
     */
    public boolean solveSymbolicFormula(JmcBooleanFormula operation) {
        return solve(operation.getFormula());
    }

    /**
     * Dissolves the given symbolic formula and returns the result.
     *
     * @param operation the symbolic operation containing the formula to dissolve.
     * @return true if the formula is unsatisfiable, false otherwise.
     */
    public boolean disSolveSymbolicFormula(JmcBooleanFormula operation) {
        return solve(negateFormula(operation));
    }

    /**
     * Solves the given boolean formula and returns the result.
     * <p>
     * This method creates a new prover environment, adds the boolean formula as a constraint, and checks if the formula
     * is satisfiable. If the formula is satisfiable, the model generated by the solver is stored in the model property.
     * The method returns true if the formula is satisfiable, and false otherwise.
     * </p>
     *
     * @param formula the boolean formula to solve.
     * @return true if the formula is satisfiable, false otherwise.
     */
    protected abstract boolean solve(BooleanFormula formula);

    /**
     * Negates the given boolean formula and returns the result.
     *
     * @param formula the boolean formula to negate.
     * @return the negated boolean formula.
     */
    public BooleanFormula negateFormula(JmcBooleanFormula formula) {
        return bmgr.not(formula.getFormula());
    }

    /**
     * Returns the JavaSMT configuration used to build the solver context.
     *
     * @return the configuration.
     */
    public Configuration getConfig() {
        return config;
    }

    /**
     * Returns the JavaSMT log manager.
     *
     * @return the log manager.
     */
    public LogManager getLogger() {
        return logger;
    }

    /**
     * Returns the JavaSMT shutdown manager for the solver context.
     *
     * @return the shutdown manager.
     */
    public ShutdownManager getShutdown() {
        return shutdown;
    }

    /**
     * Returns the active prover's map of symbolic integer variables by name.
     *
     * @return the symbolic integer variable map.
     */
    public Map<String, SymIntVariable> getSymIntVariableMap() {
        return symIntVariableMap;
    }

    /**
     * Returns the JavaSMT solver context.
     *
     * @return the solver context.
     */
    public SolverContext getContext() {
        return context;
    }

    /**
     * Returns the JavaSMT formula manager.
     *
     * @return the formula manager.
     */
    public FormulaManager getFmgr() {
        return fmgr;
    }

    /**
     * Returns the JavaSMT boolean formula manager.
     *
     * @return the boolean formula manager.
     */
    public BooleanFormulaManager getBmgr() {
        return bmgr;
    }

    /**
     * Returns the JavaSMT integer formula manager.
     *
     * @return the integer formula manager.
     */
    public IntegerFormulaManager getImgr() {
        return imgr;
    }

    /**
     * Returns the model from the last satisfiable check, or {@code null} if none.
     *
     * @return the current model.
     */
    public Model getModel() {
        return model;
    }

    /**
     * Returns the symbolic integer variable with the given name.
     * <p>
     * This method checks if the symbolic integer variable with the given name already exists in the symIntVariableMap.
     * If the variable exists, it returns the existing variable. Otherwise, it creates a new symbolic integer variable
     * with the given name, stores it in the symIntVariableMap, and returns the new variable.
     * </p>
     *
     * @param name the name of the symbolic integer variable to retrieve.
     * @return the symbolic integer variable with the given name.
     */
    public SymIntVariable getSymIntVariable(String name) {
        if (symIntVariableMap.containsKey(name)) {
            //Returning existing SymIntVariable
            return symIntVariableMap.get(name);
        } else {
            //Creating new SymIntVariable
            NumeralFormula.IntegerFormula symInt = imgr.makeVariable(name);
            SymIntVariable variable = new SymIntVariable(symInt);
            symIntVariableMap.put(name, variable);
            return variable;
        }
    }

    /**
     * Returns the current concrete value of the named symbolic integer variable.
     *
     * @param name the variable name.
     * @return the concrete value.
     * @throws RuntimeException if no such variable exists.
     */
    public int getSymIntVarValue(String name) {
        if (symIntVariableMap.containsKey(name)) {
            return symIntVariableMap.get(name).getValue();
        } else {
            throw new RuntimeException("Symbolic integer variable not found: " + name);
        }
    }

    /**
     * Returns the symbolic boolean variable with the given name.
     * <p>
     * This method checks if the symbolic boolean variable with the given name already exists in the symBoolVariableMap.
     * If the variable exists, it returns the existing variable. Otherwise, it creates a new symbolic boolean variable
     * with the given name, stores it in the symBoolVariableMap, and returns the new variable.
     * </p>
     *
     * @param name the name of the symbolic boolean variable to retrieve.
     * @return the symbolic boolean variable with the given name.
     */
    public SymBoolVariable getSymBoolVariable(String name) {
        if (symBoolVariableMap.containsKey(name)) {
            //Return an existing SymBoolVariable
            return symBoolVariableMap.get(name);
        } else {
            //Create a new SymBoolVariable
            BooleanFormula symBool = bmgr.makeVariable(name);
            SymBoolVariable variable = new SymBoolVariable(symBool);
            symBoolVariableMap.put(name, variable);
            return variable;
        }
    }

    /**
     * Returns the current concrete value of the named symbolic boolean variable.
     *
     * @param name the variable name.
     * @return the concrete value.
     * @throws RuntimeException if no such variable exists.
     */
    public boolean getSymBoolVarValue(String name) {
        if (symBoolVariableMap.containsKey(name)) {
            return symBoolVariableMap.get(name).getValue();
        } else {
            throw new RuntimeException("Symbolic boolean variable not found: " + name);
        }
    }

    /**
     * Returns whether the active prover currently holds no constraints.
     *
     * @return true if the prover is fresh.
     */
    public boolean isFreshProver() {
        return freshProver;
    }

    /**
     * Sets the fresh-prover flag (set by the algorithm when it switches prover contexts).
     *
     * @param resetProver the new flag value.
     */
    public void setFreshProverFlag(boolean resetProver) {
        this.freshProver = resetProver;
    }

    /**
     * Pushes the given constraint onto the active prover's stack.
     *
     * @param formula the constraint to assert.
     */
    public void addFormula(JmcBooleanFormula formula) {
        push(formula);
    }

    /**
     * Pushes the negation of the given constraint onto the active prover's stack.
     *
     * @param formula the constraint whose negation to assert.
     */
    public void addNegatedFormula(JmcBooleanFormula formula) {
        push(negateFormula(formula));
    }

    /** Pops the top constraint off the active prover's stack. */
    public abstract void pop();

    /** Pushes an empty backtracking level onto the active prover's stack. */
    protected abstract void push();

    /**
     * Pushes a JavaSMT boolean formula onto the active prover's stack.
     *
     * @param formula the formula to assert.
     */
    protected abstract void push(BooleanFormula formula);

    /**
     * Pushes a symbolic constraint onto the active prover's stack.
     *
     * @param operation the constraint to assert.
     */
    protected abstract void push(JmcBooleanFormula operation);

    /**
     * Evaluates a new constraint-evaluation event: computes the branch taken now and whether the
     * other branch is feasible, updating the prover stack accordingly.
     *
     * @param symbolicOperation the constraint being evaluated.
     * @return the {@link SolverResult} (branch outcome + negatability).
     */
    public abstract SolverResult computeNewSymbolicOperation(JmcBooleanFormula symbolicOperation);

    /**
     * Evaluates a symbolic {@code assume}: returns whether the constraint is satisfiable and asserts
     * it (or rolls back) accordingly.
     *
     * @param symbolicOperation the assumed constraint.
     * @return true if the assumption holds.
     */
    public abstract boolean computeNewSymAssumeOperation(JmcBooleanFormula symbolicOperation);

    /**
     * Replays a symbolic {@code assume} during guided re-execution, asserting the (already decided)
     * constraint and refreshing the model.
     *
     * @param symbolicOperation the assumed constraint.
     */
    public abstract void computeGuidedSymAssumeOperation(JmcBooleanFormula symbolicOperation);

    /**
     * Evaluates a symbolic {@code assert}: returns whether the property necessarily holds (its
     * negation is unsatisfiable).
     *
     * @param symbolicOperation the asserted constraint.
     * @return true if the assertion cannot be violated.
     */
    public abstract boolean computeNewSymAssertOperation(JmcBooleanFormula symbolicOperation);

    /** Solves the current constraint stack and refreshes the concrete model from the solution. */
    public abstract void solveAndUpdateModel();

    /**
     * Creates a new prover context (reusing a pooled one when available).
     *
     * @return the new prover state.
     */
    public abstract ProverState createNewProver();

    /**
     * Makes the given prover state the active one, under the given logical id.
     *
     * @param proverState the prover state to activate.
     * @param proverId the logical prover id.
     */
    public abstract void setProver(ProverState proverState, int proverId);

    /**
     * Returns the logical id of the active prover.
     *
     * @return the active prover id.
     */
    public abstract int getProverId();

    /**
     * Empties the given prover's constraint stack.
     *
     * @param prover the prover environment to reset.
     */
    public abstract void resetProver(ProverEnvironment prover);

    /** Empties the active prover's constraint stack. */
    public abstract void resetCurrentProver();
}
