package org.mpi_sws.jmc.solver;

import org.mpi_sws.jmc.symbolic.array.SymArrayVariable;
import org.mpi_sws.jmc.symbolic.bool.JmcBooleanFormula;
import org.mpi_sws.jmc.symbolic.bool.SymBoolVariable;
import org.mpi_sws.jmc.symbolic.integer.SymIntVariable;
import org.sosy_lab.common.ShutdownManager;
import org.sosy_lab.common.configuration.Configuration;
import org.sosy_lab.common.configuration.InvalidConfigurationException;
import org.sosy_lab.common.log.BasicLogManager;
import org.sosy_lab.common.log.LogManager;
import org.sosy_lab.java_smt.SolverContextFactory;
import org.sosy_lab.java_smt.api.*;

import java.util.HashMap;
import java.util.Map;

/**
 * The SymbolicSolver class is a core component designed for solving symbolic formulas within the program under the test.
 * It encapsulates the functionality for manipulating and solving symbolic representations of boolean and integer
 * variables. This class leverages the JavaSMT API to interface with various SMT (Satisfiability Modulo Theories) solvers,
 * providing a unified API for theorem proving tasks.
 * <p>
 * The class supports operations such as solving symbolic formulas, negating formulas, and creating dependency formulas
 * from a list of symbolic operations. It allows for the dynamic selection of SMT solvers based on the provided solver type,
 * enabling flexibility in choosing the underlying solver based on the specific requirements of the verification task.
 * <p>
 * SymbolicSolver initializes with a configuration, a logging manager, and a shutdown manager to handle the lifecycle
 * of the solver context. It provides methods to access and manipulate symbolic variables (both boolean and integer),
 * facilitating the creation of complex symbolic expressions that programmer can use.
 */
public abstract class SymbolicSolver {

    /**
     * @property {@link #config} used to store the configuration settings for the solver context.
     */
    private final Configuration config;

    /**
     * @property {@link #logger} used to manage logging and output messages from the solver.
     */
    private final LogManager logger;

    /**
     * @property {@link #shutdown} used to manage the shutdown and cleanup of the solver context.
     */
    private final ShutdownManager shutdown;

    /**
     * @property {@link #symIntVariableMap} used to store the mapping of symbolic integer variables to their names.
     */
    public Map<String, SymIntVariable> symIntVariableMap = new HashMap<>();

    /**
     * @property {@link #symBoolVariableMap} used to store the mapping of symbolic boolean variables to their names.
     */
    public Map<String, SymBoolVariable> symBoolVariableMap = new HashMap<>();

    /**
     * @property {@link #symArrayVariableMap} used to store the mapping of symbolic array variables to their names.
     */
    public Map<String, SymArrayVariable> symArrayVariableMap = new HashMap<>();
    /**
     * @property {@link #context} used to store the solver context for interacting with the SMT solver.
     */
    protected SolverContext context;

    /**
     * @property {@link #fmgr} used to access the formula manager for creating and manipulating formulas.
     */
    protected FormulaManager fmgr;

    /**
     * @property {@link #bmgr} used to access the boolean formula manager for boolean operations.
     */
    protected BooleanFormulaManager bmgr;

    /**
     * @property {@link #imgr} used to access the integer formula manager for integer operations.
     */
    protected IntegerFormulaManager imgr;

    /**
     * @property {@link #bmgr} used to access the array formula manager for array operations.
     */
    protected ArrayFormulaManager amgr;

    /**
     * @property {@link #model} used to store the model generated by the solver for a satisfiable formula.
     */
    protected Model model;

    private boolean freshProver = true;

    private long solverTime = 0L;

    /**
     * Constructs a new instance of the SymbolicSolver class with the default SMT solver type (SMTInterpol).
     */
    public SymbolicSolver() {
        this(SMTSolverTypes.Z3); // Default to Z3 solver
    }

    /**
     * Constructs a new instance of the SymbolicSolver class with the specified SMT solver type.
     *
     * @param type the type of SMT solver to use for solving symbolic formulas.
     */
    public SymbolicSolver(SMTSolverTypes type) {
        SolverContextFactory.Solvers solverType = findSolverType(type);
        try {
            long startTime = System.nanoTime();
            config = Configuration.builder().build();
            logger = BasicLogManager.create(config);
            shutdown = ShutdownManager.create();
            context = SolverContextFactory.createSolverContext(
                    config, logger, shutdown.getNotifier(), solverType
            );
            fmgr = context.getFormulaManager();
            bmgr = fmgr.getBooleanFormulaManager();
            imgr = fmgr.getIntegerFormulaManager();
            amgr = fmgr.getArrayFormulaManager();
            long endTime = System.nanoTime();
            incSolverTime(endTime - startTime);
        } catch (InvalidConfigurationException e) {
            throw new RuntimeException("Error creating solver context", e);
        }
    }

    protected void incSolverTime(long time) {
        solverTime += time;
    }

    public long getSolverTime() {
        return solverTime;
    }

    /**
     * Finds the corresponding SolverContextFactory.Solvers enum value for the given SMTSolverTypes enum value.
     *
     * @param type the type of SMT solver to find the corresponding enum value for.
     * @return the corresponding SolverContextFactory.Solvers enum value.
     */
    public SolverContextFactory.Solvers findSolverType(SMTSolverTypes type) {
        return switch (type) {
            case OPENSMT -> SolverContextFactory.Solvers.OPENSMT;
            case MATHSAT5 -> SolverContextFactory.Solvers.MATHSAT5;
            case SMTINTERPOL -> SolverContextFactory.Solvers.SMTINTERPOL;
            case Z3 -> SolverContextFactory.Solvers.Z3;
            case PRINCESS -> SolverContextFactory.Solvers.PRINCESS;
            case BOOLECTOR -> SolverContextFactory.Solvers.BOOLECTOR;
            case CVC4 -> SolverContextFactory.Solvers.CVC4;
            case CVC5 -> SolverContextFactory.Solvers.CVC5;
            case YICES2 -> SolverContextFactory.Solvers.YICES2;
        };
    }

    public abstract int size();

    /**
     * Solves the given symbolic formula and returns the result.
     *
     * @param operation the symbolic operation containing the formula to solve.
     * @return true if the formula is satisfiable, false otherwise.
     */
    public boolean solveSymbolicFormula(JmcBooleanFormula operation) {
        return solve(operation.getFormula());
    }

    /**
     * Dissolves the given symbolic formula and returns the result.
     *
     * @param operation the symbolic operation containing the formula to dissolve.
     * @return true if the formula is unsatisfiable, false otherwise.
     */
    public boolean disSolveSymbolicFormula(JmcBooleanFormula operation) {
        return solve(negateFormula(operation));
    }

    /**
     * Solves the given boolean formula and returns the result.
     * <p>
     * This method creates a new prover environment, adds the boolean formula as a constraint, and checks if the formula
     * is satisfiable. If the formula is satisfiable, the model generated by the solver is stored in the model property.
     * The method returns true if the formula is satisfiable, and false otherwise.
     * </p>
     *
     * @param formula the boolean formula to solve.
     * @return true if the formula is satisfiable, false otherwise.
     */
    protected abstract boolean solve(org.sosy_lab.java_smt.api.BooleanFormula formula);

    /**
     * Negates the given boolean formula and returns the result.
     *
     * @param formula the boolean formula to negate.
     * @return the negated boolean formula.
     */
    public org.sosy_lab.java_smt.api.BooleanFormula negateFormula(JmcBooleanFormula formula) {
        return bmgr.not(formula.getFormula());
    }

    public Configuration getConfig() {
        return config;
    }

    public LogManager getLogger() {
        return logger;
    }

    public ShutdownManager getShutdown() {
        return shutdown;
    }

    public Map<String, SymIntVariable> getSymIntVariableMap() {
        return symIntVariableMap;
    }

    public SolverContext getContext() {
        return context;
    }

    public FormulaManager getFmgr() {
        return fmgr;
    }

    public BooleanFormulaManager getBmgr() {
        return bmgr;
    }

    public IntegerFormulaManager getImgr() {
        return imgr;
    }

    public Model getModel() {
        return model;
    }

    /**
     * Returns the symbolic integer variable with the given name.
     * <p>
     * This method checks if the symbolic integer variable with the given name already exists in the symIntVariableMap.
     * If the variable exists, it returns the existing variable. Otherwise, it creates a new symbolic integer variable
     * with the given name, stores it in the symIntVariableMap, and returns the new variable.
     * </p>
     *
     * @param name the name of the symbolic integer variable to retrieve.
     * @return the symbolic integer variable with the given name.
     */
    public SymIntVariable getSymIntVariable(String name) {
        if (symIntVariableMap.containsKey(name)) {
            //Returning existing SymIntVariable
            return symIntVariableMap.get(name);
        } else {
            //Creating new SymIntVariable
            NumeralFormula.IntegerFormula symInt = imgr.makeVariable(name);
            SymIntVariable variable = new SymIntVariable(symInt);
            symIntVariableMap.put(name, variable);
            return variable;
        }
    }

    public int getSymIntVarValue(String name) {
        if (symIntVariableMap.containsKey(name)) {
            return symIntVariableMap.get(name).getValue();
        } else {
            throw new RuntimeException("Symbolic integer variable not found: " + name);
        }
    }

    /**
     * Returns the symbolic boolean variable with the given name.
     * <p>
     * This method checks if the symbolic boolean variable with the given name already exists in the symBoolVariableMap.
     * If the variable exists, it returns the existing variable. Otherwise, it creates a new symbolic boolean variable
     * with the given name, stores it in the symBoolVariableMap, and returns the new variable.
     * </p>
     *
     * @param name the name of the symbolic boolean variable to retrieve.
     * @return the symbolic boolean variable with the given name.
     */
    public SymBoolVariable getSymBoolVariable(String name) {
        if (symBoolVariableMap.containsKey(name)) {
            //Return an existing SymBoolVariable
            return symBoolVariableMap.get(name);
        } else {
            //Create a new SymBoolVariable
            org.sosy_lab.java_smt.api.BooleanFormula symBool = bmgr.makeVariable(name);
            SymBoolVariable variable = new SymBoolVariable(symBool);
            symBoolVariableMap.put(name, variable);
            return variable;
        }
    }

    public boolean getSymBoolVarValue(String name) {
        if (symBoolVariableMap.containsKey(name)) {
            return symBoolVariableMap.get(name).getValue();
        } else {
            throw new RuntimeException("Symbolic boolean variable not found: " + name);
        }
    }

    public boolean isFreshProver() {
        return freshProver;
    }

    public void setFreshProverFlag(boolean resetProver) {
        this.freshProver = resetProver;
    }

    public void addFormula(JmcBooleanFormula formula) {
        push(formula);
    }

    public void addNegatedFormula(JmcBooleanFormula formula) {
        push(negateFormula(formula));
    }

    protected abstract void pop();

    protected abstract void push();

    protected abstract void push(org.sosy_lab.java_smt.api.BooleanFormula formula);

    protected abstract void push(JmcBooleanFormula operation);

    public abstract SolverResult computeNewSymbolicOperation(JmcBooleanFormula symbolicOperation);

    public abstract boolean computeNewSymAssumeOperation(JmcBooleanFormula symbolicOperation);

    public abstract void computeGuidedSymAssumeOperation(JmcBooleanFormula symbolicOperation);

    public abstract boolean computeNewSymAssertOperation(JmcBooleanFormula symbolicOperation);

    public abstract void solveAndUpdateModel();

    public abstract ProverState createNewProver();

    public abstract void setProver(ProverState proverState, int proverId);

    public abstract int getProverId();

    public abstract void resetProver(ProverEnvironment prover);
}
