package org.mpisws.checker;

/** The JmcModelCheckerReport class represents a report generated by the JMC model checker. */
public class JmcModelCheckerReport {
    private Long totalTimeMillis;

    /** Constructs a new JmcModelCheckerReport object. */
    public JmcModelCheckerReport() {}

    public void setTotalTimeMillis(Long totalTimeMillis) {
        this.totalTimeMillis = totalTimeMillis;
    }

    public Long getTotalTimeMillis() {
        return totalTimeMillis;
    }
}
