package org.mpisws.checker;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.mpisws.instrumentation.InstrumentedTarget;
import org.mpisws.instrumentation.Instrumentor;
import org.mpisws.runtime.HaltCheckerException;
import org.mpisws.runtime.HaltExecutionException;
import org.mpisws.runtime.HaltTaskException;
import org.mpisws.runtime.JmcRuntime;
import org.mpisws.runtime.JmcRuntimeConfiguration;
import org.mpisws.runtime.RuntimeEvent;
import org.mpisws.runtime.RuntimeEventType;

/**
 * The JmcModelChecker class is responsible for managing the model checking process. It uses a
 * JmcCheckerConfiguration to configure the process and a JmcTestTarget to specify the program under
 * test.
 */
public class JmcModelChecker {

    private static final Logger LOGGER = LogManager.getLogger(JmcModelChecker.class);

    private final JmcCheckerConfiguration config;

    /** Constructs a new JMC model checker with the default configuration. */
    public JmcModelChecker() {
        this(new JmcCheckerConfiguration.Builder().build());
    }

    /**
     * Constructs a new JMC model checker with the given configuration.
     *
     * @param config the configuration to use
     */
    public JmcModelChecker(JmcCheckerConfiguration config) {
        this.config = config;
    }

    /**
     * Instruments the given test target.
     *
     * @param target the test target to instrument
     * @return the instrumented target
     */
    public JmcTestTarget instrument(JmcTestTarget target) {
        return Instrumentor.instrument(target);
    }

    /**
     * Checks the given test target. No instrumentation involved
     *
     * @param target the test target to check
     * @return the report generated by the model checker
     */
    public JmcModelCheckerReport check(JmcTestTarget target) {

        // Instrument the target if necessary
        if (!(target instanceof InstrumentedTarget)) {
            target = instrument(target);
        }

        JmcRuntimeConfiguration runtimeConfig = config.toRuntimeConfiguration();
        JmcRuntime.setup(runtimeConfig);
        JmcModelCheckerReport report = new JmcModelCheckerReport();
        Long startTime = System.currentTimeMillis();
        int numIterations = config.getNumIterations();
        try {
            for (int i = 0; i < numIterations; i++) {
                try {
                    JmcRuntime.initIteration(i);
                    target.invoke();
                    RuntimeEvent mainEndEvent =
                            new RuntimeEvent.Builder()
                                    .type(RuntimeEventType.FINISH_EVENT)
                                    .taskId(1L)
                                    .build();
                    JmcRuntime.updateEvent(mainEndEvent);
                    JmcRuntime.resetIteration(i);
                } catch (HaltTaskException e) {
                    LOGGER.debug(
                            "Halting execution: {} due to main thread halted: {}",
                            i,
                            e.getMessage());
                    break;
                } catch (HaltExecutionException e) {
                    LOGGER.error("Halting execution: {} due to exception: {}", i, e.getMessage());
                    break;
                } catch (AssertionError e) {
                    LOGGER.error("Assertion error in iteration {}: {}", i, e.getMessage());
                    break;
                }
            }
        } catch (HaltCheckerException e) {
            if (e.isOkay()) {
                LOGGER.info("Model checking completed successfully.");
            } else {
                LOGGER.error("Model checking failed: {}", e.getMessage());
                System.exit(1);
            }
        } finally {
            Long endTime = System.currentTimeMillis();
            JmcRuntime.tearDown();
            report.setTotalTimeMillis(endTime - startTime);
        }
        return report;
    }
}
